[build]
	publish = "export"
	command = "npm run export"

[[headers]]
	for = "/*"
	[headers.values]
		X-Content-Type-Options = "nosniff"
		X-Frame-Options = "SAMEORIGIN"
		X-XSS-Protection = "1; mode=block"
		Content-Security-Policy = "default-src 'self' 'unsafe-inline'; connect-src 'self' https://api.tides.app; report-uri https://bdougherty.report-uri.com/r/d/csp/enforce; upgrade-insecure-requests"
		Cross-Origin-Window-Policy = "deny"
		Feature-Policy = "geolocation 'self'; camera 'none'; fullscreen 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; notifications 'none'; payment 'none'; push 'none'; speaker 'none'; sync-xhr 'none'; vibrate 'none'"
		Referrer-Policy = "strict-origin-when-cross-origin"
